### ISSUE TITLE
col Source_Form_ID in borrowings.csv

### ISSUE THREAD

**Issue by martino-vic** [lexibank/uralex#15]
uralex/cldf/borrowings.csv has a column called "Source_Form_ID" which is completely empty, as far as I can see... I was wondering what the purpose of that column is

**Comment by kasyrj** [comment]
As I understand, that column would reference a key of a loanword's source form in a CLDF dataset (e.g. https://cldf.clld.org/v1.0/terms.html). UraLex does not include keys such as this as part of its raw data content (which is found in the 'raw' folder, and where the CLDF format of the dataset is generated from), which is likely the reason why they are empty in the CLDF version of the data, as well.

**Comment by xrotwang** [comment]
Yes - sorry for chiming in so late - @kasyrj is right in that this column is basically an artefact of the CLDF format.
